spring:
  application:
    name: cinema

  datasource:
    url: jdbc:mysql://localhost:3306/cinema_booking
    username: root
    password: 27102005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: LALALALA36PHUNGTHANHDO18ANHDOMIXI36CAMONANHANHDOMIXI
    expiration: 3600000
